export const differentPrayers = [
  {
    title: "Fajr",
    rakats: "2 Sunnah → 2 Fard",
    subheading: "Steps to Perform Fajr Salah",
    description: [
      "Make niyyah (intention) silently in your heart: *Nawaytu an usalliya rak‘atay al-fajri fardan lillahi ta‘ala*.",
      "Raise both hands and say Takbir: *Allahu Akbar*.",
      "Recite the opening supplication (Sana): *Subhanaka Allahumma wa bihamdika wa tabarakasmuka wa ta‘ala jadduka wa la ilaha ghayruk*.",
      "Recite *Surah Al-Fatiha*.",
      "Recite any short *Surah* or a few verses from the *Qur’an*.",
      "Perform *Ruku* (bowing), saying *Subhana Rabbiyal 'Azeem* three times.",
      "Stand up straight (*Qawmah*) and say: *Sami’ Allahu liman hamidah, Rabbana lakal hamd*.",
      "Go down for *Sujood* (prostration), saying *Subhana Rabbiyal A‘la* three times.",
      "Sit briefly between the two *Sujoods* (*Jalsa*) and then perform the second *Sujood*.",
      "Stand for the second rak‘ah and repeat the same steps as above.",
      "After the second *Sujood* of the second rak‘ah, sit for *Tashahhud* and recite the testimony.",
      "End the prayer by turning your head to the right and left, saying *Assalamu Alaikum wa Rahmatullah*.",
    ],
  },
  {
    title: "Dhuhr",
    rakats: "4 Sunnah → 4 Fard → 2 Sunnah",
    subheading: "Steps to Perform Dhuhr Salah",
    description: [
      "Make niyyah (intention) silently in your heart: *Nawaytu an usalliya arba‘a rak‘atin fard az-zuhri lillahi ta‘ala*.",
      "Raise both hands and say Takbir: *Allahu Akbar*.",
      "Recite the opening supplication (Sana): *Subhanaka Allahumma wa bihamdika wa tabarakasmuka wa ta‘ala jadduka wa la ilaha ghayruk*.",
      "Recite *Surah Al-Fatiha*.",
      "Recite any short *Surah* or a few verses from the *Qur’an*.",
      "Perform *Ruku* (bowing), saying *Subhana Rabbiyal 'Azeem* three times.",
      "Stand up straight (*Qawmah*) and say: *Sami’ Allahu liman hamidah, Rabbana lakal hamd*.",
      "Go down for *Sujood* (prostration), saying *Subhana Rabbiyal A‘la* three times.",
      "Sit briefly between the two *Sujoods* (*Jalsa*) and then perform the second *Sujood*.",
      "Stand for the second rak‘ah and repeat the same steps.",
      "After the second *Sujood* of the second rak‘ah, sit for *Tashahhud*, then stand for the third rak‘ah.",
      "Repeat the steps for the third and fourth rak‘ah.",
      "After the final *Sujood* of the fourth rak‘ah, sit for the complete *Tashahhud* (including Salawat and Du’a).",
      "End the prayer by turning your head to the right and left, saying *Assalamu Alaikum wa Rahmatullah*.",
    ],
  },
  {
    title: "Asr",
    rakats: "4 Sunnah → 4 Fard",
    subheading: "Steps to Perform Asr Salah",
    description: [
      "Make niyyah (intention) silently in your heart: *Nawaytu an usalliya arba‘a rak‘atin fard al-‘asri lillahi ta‘ala*.",
      "Raise both hands and say Takbir: *Allahu Akbar*.",
      "Recite the opening supplication (Sana): *Subhanaka Allahumma wa bihamdika wa tabarakasmuka wa ta‘ala jadduka wa la ilaha ghayruk*.",
      "Recite *Surah Al-Fatiha*.",
      "Recite any short *Surah* or a few verses from the *Qur’an*.",
      "Perform *Ruku* (bowing), saying *Subhana Rabbiyal 'Azeem* three times.",
      "Stand up straight (*Qawmah*) and say: *Sami’ Allahu liman hamidah, Rabbana lakal hamd*.",
      "Go down for *Sujood* (prostration), saying *Subhana Rabbiyal A‘la* three times.",
      "Sit briefly between the two *Sujoods* (*Jalsa*) and then perform the second *Sujood*.",
      "Stand for the second rak‘ah and repeat the same steps.",
      "After the second *Sujood* of the second rak‘ah, sit for *Tashahhud*, then stand for the third rak‘ah.",
      "Repeat the steps for the third and fourth rak‘ah.",
      "After the final *Sujood* of the fourth rak‘ah, sit for the complete *Tashahhud* (including Salawat and Du’a).",
      "End the prayer by turning your head to the right and left, saying *Assalamu Alaikum wa Rahmatullah*.",
    ],
  },
  {
    title: "Maghrib",
    rakats: "3 Fard → 2 Sunnah",
    subheading: "Steps to Perform Maghrib Salah",
    description: [
      "Make niyyah (intention) silently in your heart: *Nawaytu an usalliya thalātha rak‘ātin fard al-maghrib lillahi ta‘ala*.",
      "Raise both hands and say Takbir: *Allahu Akbar*.",
      "Recite the opening supplication (Sana): *Subhanaka Allahumma wa bihamdika wa tabarakasmuka wa ta‘ala jadduka wa la ilaha ghayruk*.",
      "Recite *Surah Al-Fatiha*.",
      "Recite any short *Surah* or a few verses from the *Qur’an*.",
      "Perform *Ruku* (bowing), saying *Subhana Rabbiyal 'Azeem* three times.",
      "Stand up straight (*Qawmah*) and say: *Sami’ Allahu liman hamidah, Rabbana lakal hamd*.",
      "Go down for *Sujood* (prostration), saying *Subhana Rabbiyal A‘la* three times.",
      "Sit briefly between the two *Sujoods* (*Jalsa*) and then perform the second *Sujood*.",
      "Stand for the second rak‘ah and repeat the same steps.",
      "After the second *Sujood* of the second rak‘ah, sit for *Tashahhud*, then stand for the third rak‘ah.",
      "In the third rak‘ah, recite only *Surah Al-Fatiha* (without additional *Surah*).",
      "Complete *Ruku*, *Sujood*, and after the final *Sujood*, sit for full *Tashahhud* (including Salawat and Du’a).",
      "End the prayer by turning your head to the right and left, saying *Assalamu Alaikum wa Rahmatullah*.",
    ],
  },
  {
    title: "Isha",
    rakats: "4 Sunnah → 4 Fard → 2 Sunnah → 3 Witr",
    subheading: "Steps to Perform Isha Salah",
    description: [
      "Make niyyah (intention) silently in your heart: *Nawaytu an usalliya arba‘a rak‘atin fard al-‘isha’ lillahi ta‘ala*.",
      "Raise both hands and say Takbir: *Allahu Akbar*.",
      "Recite the opening supplication (Sana): *Subhanaka Allahumma wa bihamdika wa tabarakasmuka wa ta‘ala jadduka wa la ilaha ghayruk*.",
      "Recite *Surah Al-Fatiha*.",
      "Recite any short *Surah* or a few verses from the *Qur’an*.",
      "Perform *Ruku* (bowing), saying *Subhana Rabbiyal 'Azeem* three times.",
      "Stand up straight (*Qawmah*) and say: *Sami’ Allahu liman hamidah, Rabbana lakal hamd*.",
      "Go down for *Sujood* (prostration), saying *Subhana Rabbiyal A‘la* three times.",
      "Sit briefly between the two *Sujoods* (*Jalsa*) and then perform the second *Sujood*.",
      "Stand for the second rak‘ah and repeat the same steps.",
      "After the second *Sujood* of the second rak‘ah, sit for *Tashahhud*, then stand for the third rak‘ah.",
      "Repeat steps for the third and fourth rak‘ah (in the third rak‘ah, *Surah Al-Fatiha* only).",
      "After the final *Sujood*, sit for the full *Tashahhud* (including Salawat and Du’a).",
      "End the prayer by turning your head to the right and left, saying *Assalamu Alaikum wa Rahmatullah*.",
    ],
  },
  {
    title: "Witr",
    rakats: "3 Witr (odd prayer)",
    subheading: "Steps to Perform Witr Salah",
    description: [
      "Make niyyah (intention) silently in your heart: *Nawaytu an usalliya thalātha rak‘ātin witr lillahi ta‘ala*.",
      "Raise both hands and say Takbir: *Allahu Akbar*.",
      "Recite the opening supplication (Sana): *Subhanaka Allahumma wa bihamdika wa tabarakasmuka wa ta‘ala jadduka wa la ilaha ghayruk*.",
      "Recite *Surah Al-Fatiha*.",
      "Recite any short *Surah* or a few verses from the *Qur’an*.",
      "Perform *Ruku*, then *Sujood* and stand for the second rak‘ah and repeat.",
      "After the second *Sujood*, stand for the third rak‘ah.",
      "After reciting *Surah Al-Fatiha* and another *Surah*, raise both hands and say *Allahu Akbar*, then recite *Dua al-Qunoot*.",
      "Complete *Ruku*, *Sujood*, and after the final *Sujood*, sit for full *Tashahhud*.",
      "End the prayer by turning your head to the right and left, saying *Assalamu Alaikum wa Rahmatullah*.",
    ],
  },
  {
    title: "Tahajjud (Night Prayer)",
    rakats: "Minimum 2 Rakat (usually prayed in sets of 2, up to 8 or more)",
    subheading: "Steps to Perform Tahajjud Salah",
    description: [
      "Make niyyah (intention) silently in your heart: *Nawaytu an usalliya rak‘atay tahajjud lillahi ta‘ala*.",
      "Begin the prayer by saying *Allahu Akbar* while raising both hands.",
      "Recite the opening supplication (*Sana*): *Subhanaka Allahumma wa bihamdika wa tabarakasmuka wa ta‘ala jadduka wa la ilaha ghayruk*.",
      "Recite *Surah Al-Fatiha* followed by any short *Surah* or verses from the *Qur’an*.",
      "Perform *Ruku* (bowing), saying *Subhana Rabbiyal ‘Azeem* three times.",
      "Stand back up (*Qawmah*) and say: *Sami’ Allahu liman hamidah, Rabbana lakal hamd*.",
      "Go down for *Sujood* (prostration), saying *Subhana Rabbiyal A‘la* three times.",
      "Sit briefly (*Jalsa*) between the two *Sujoods*, then perform the second *Sujood*.",
      "Stand for the next rak‘ah and repeat the steps.",
      "After completing two rak‘ahs, sit for *Tashahhud* and end with *Tasleem* to the right and left: *Assalamu Alaikum wa Rahmatullah*.",
      "Tahajjud is best prayed in the last third of the night after waking up from sleep.",
    ],
  },
  {
    title: "Salat al-Janazah (Funeral Prayer)",
    rakats: "4 Takbirs (No Ruku or Sujood)",
    subheading: "Steps to Perform Janazah Salah",
    description: [
      "Make niyyah (intention) silently in your heart: *Nawaytu an usalliya ‘ala hadhal mayyit salat al-janazah lillahi ta‘ala*.",
      "Say the first *Takbir* (*Allahu Akbar*) and recite *Surah Al-Fatiha*.",
      "Say the second *Takbir* (*Allahu Akbar*) and recite *Salat al-Ibrahimiyyah* (the same durood recited in Tashahhud).",
      "Say the third *Takbir* (*Allahu Akbar*) and make *du‘a* for the deceased. Example: *Allahummaghfir lahu warhamhu wa ‘afihi wa‘fu ‘anhu...* (or any authentic du‘a for the dead).",
      "Say the fourth *Takbir* (*Allahu Akbar*), then make a short concluding supplication and end with *Tasleem* to the right (some scholars recommend to both sides): *Assalamu Alaikum wa Rahmatullah*.",
      "There is no *Ruku*, *Sujood*, or Qiyam after the Takbirs in Janazah prayer.",
    ],
  },
  {
    title: "Eid al-Fitr",
    rakats: "2 Rak‘ah (no Adhan or Iqamah)",
    subheading: "Steps to Perform Eid al-Fitr Salah",
    description: [
      "Make niyyah (intention) silently in your heart: *Nawaytu an usalliya rak‘atay salat al-Eid lillahi ta‘ala*.",
      "Raise both hands and say Takbir: *Allahu Akbar*.",
      "In the first rak‘ah, after saying Takbir al-Ihram, recite 6 additional *Takbirat* (raising hands each time), pausing briefly between each.",
      "Recite *Surah Al-Fatiha*.",
      "Recite any short *Surah* or verses from the *Qur’an* (commonly *Surah Al-A‘la*).",
      "Perform *Ruku* and *Sujood* as in a normal prayer.",
      "Stand for the second rak‘ah and recite 5 additional *Takbirat*, pausing between each.",
      "Recite *Surah Al-Fatiha*.",
      "Recite any short *Surah* (commonly *Surah Al-Ghashiyah*).",
      "Complete *Ruku*, *Sujood*, and sit for *Tashahhud*.",
      "End the prayer by turning your head to the right and left, saying *Assalamu Alaikum wa Rahmatullah*.",
      "After the prayer, the Imam delivers two *Khutbahs* (sermons) — listening to them is recommended.",
    ],
  },
  {
    title: "Eid al-Adha",
    rakats: "2 Rak‘ah (no Adhan or Iqamah)",
    subheading: "Steps to Perform Eid al-Adha Salah",
    description: [
      "Make niyyah (intention) silently in your heart: *Nawaytu an usalliya rak‘atay salat al-Eid lillahi ta‘ala*.",
      "Raise both hands and say Takbir: *Allahu Akbar*.",
      "In the first rak‘ah, after Takbir al-Ihram, recite 6 additional *Takbirat*, raising hands and pausing between each.",
      "Recite *Surah Al-Fatiha*.",
      "Recite any short *Surah* or verses from the *Qur’an* (commonly *Surah Al-A‘la*).",
      "Perform *Ruku* and *Sujood* as in a normal prayer.",
      "Stand for the second rak‘ah and recite 5 additional *Takbirat*.",
      "Recite *Surah Al-Fatiha*.",
      "Recite any short *Surah* (commonly *Surah Al-Ghashiyah*).",
      "Complete *Ruku*, *Sujood*, and sit for *Tashahhud*.",
      "End the prayer by turning your head to the right and left, saying *Assalamu Alaikum wa Rahmatullah*.",
      "After the prayer, the Imam delivers two *Khutbahs* — it is encouraged to listen attentively.",
    ],
  },
];
